apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  ports:
    - port: 80 # Getting traffic from port 80
      targetPort: 3000 # Sending traffic to port 3000
  selector:
    app: hello # Selecting pods with label app: hello

# kubectl port-forward service/hello-svc 8080:80
# this is for deugging purposes
# to check if the service is working
