apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: hello
      image: aecceyhan/codeseouldemo:v1
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: app-secret
        - configMapRef:
            name: app-config
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
